config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/cv'
  root 'welcome#index'

  get '*path' => redirect('/')
  
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attributes :email,    :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message,  :validate => true
  attributes :nickname, :captcha => true

  def headers
    {
      subject: "Contact Form",
      to: "charlesdebarros@yahoo.co.uk",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
# Post model
class Post < ActiveRecord::Base
  validates :title, :content, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
# Project model
class Project < ActiveRecord::Base
  validates :title, :link, :description, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
# User model for Devise gem
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable,
         :trackable, :validatable # , :registerable,
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
      if @contact.deliver
        flash[:error] = nil
      else
        flash[:error] = 'Unable to send message'
        render :new
      end
  end
end

app/controllers/posts_controller.rb
# Post Controller
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Post successfully created'
      redirect_to '/posts'
    else
      flash[:alert] = 'Unable to add post'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      flash[:notice] = 'The post has been successfully updated'
      redirect_to @post
    else
      flash[:alert] = 'Unable to update post'
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = 'Post successfully deleted!'
    redirect_to '/posts'
  end

  private

  def find_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end
end

app/controllers/projects_controller.rb
# Projects controller
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order('created_at DESC')
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:notice] = 'Project successfully created'
      redirect_to '/projects'
    else
      flash[:alert] = 'Unable to create project'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update project_params
      flash[:notice] = 'The project has been successfully updated.'
      redirect_to @project
    else
      flash[:alert] = 'Unable to update project.'
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = 'Project successfully deleted!'
    redirect_to '/projects'
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/controllers/welcome_controller.rb
# Welcome controller
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
    @projects = Project.all.order('created_at DESC')
  end

  def show
    @welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page-title">Say Hello!</h1>
<div class="skinny-wrapper wrapper-padding">
  <h1>Thank you for your message!</h1>
  <p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page-title">Say Hello!</h1>
<div class="skinny-wrapper wrapper-padding">
  <%= form_for @contact do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: 'Your name' %>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email, required: true, placeholder: 'Your e-mail' %>
    <br>
    <%= f.label :message %>
    <%= f.text_area :message, as: :text, placeholder: 'Please enter your message here' %>

    <div class="hidden">
      <%= f.label :nickname %>
      <%= f.text_field :nickname, hint: 'Leave this field blank' %>
    </div>
    <%= f.submit 'Send message', class: "button" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-123170863-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-123170863-1');
    </script>
    <title>Charles De Barros - Wed/Software developer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="container-fluid">
    <header id="main-navigation" class="clearfix">
      <%= link_to 'Charles De Barros', root_path, class: 'name' %>
      <nav>
        <% link_to 'Articles', posts_path %>
        <%= link_to 'Projects', projects_path %>
        <%= link_to 'Contact', new_contact_path %>
        <%= link_to 'CV', welcome_cv_path %>
        <% if user_signed_in? %>
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        <% end %>
      </nav>
    </header>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <footer id="main-footer">
      <p class="copyright">&copy; 2015-2019 Charles De Barros</p>
      <nav>
        <a href="https://github.com/charlesdebarros/" target="_blank"><i class="fa fa-github"></i></a>
        <a href="https://uk.linkedin.com/in/charlesdebarros" target="_blank"><i class="fa fa-linkedin"></i></a>
        <a href="https://twitter.com/charlesdebarros" target="_blank"><i class="fa fa-twitter"></i></a>
      </nav>
    </footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /*** CONFIGURATION VARIABLES ***/
    var disqus_shortname = 'mysite';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, { only_url: false }]) %>';
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//chat-box.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h3><%= pluralize(@post.errors.count, "error") %> prevented this post from being saved: </h3>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %> <br>
  <%= f.text_field :title, placeholder: 'Title' %>
  <br><br>
  <%= f.label :content %> <br>
  <%= f.text_area :content, placeholder: 'Your content goes here' %>
  <br><br>
  <%= f.submit %>
<% end %>
<br>
<%= link_to 'Cancel', projects_path %>

<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/edit.html.erb
<h1 id="page-title">Edit Post</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page-title">Things I've written</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <div class="post">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <p class="date"><%= post.created_at.strftime('%A, %d %b %Y') %></p>
        <h2><a href="#"><%= link_to post.title, post %></a></h2>
        <br>
        <hr>
      <% end %>
    <% else %>
      <h3>No posts added yet.</h3>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to 'Add a post', new_post_path %>
    <% end %>
  </div>
  <br>
  <%= will_paginate @posts %>
</div>
<!-- <div class="pagination">
  <span class="previous-page disabled">Previous</span>
  <em class="current">1</em>
  <a rel="next" href="">2</a>
  <a class="next-page" href="#">Next</a>
</div>
 -->

app/views/posts/new.html.erb
<h1 id="page-title">New Post</h1>
<div class="skinny-wrapper wrapper-padding">
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
  <header>
    <p class="date"><%= @post.created_at.strftime('%A, %d %b %Y') %></p>
    <h1><%= @post.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @post.content %><br><br>
  </div>

  <% if user_signed_in? %>
    <div id="admin-links">
      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
    </div>
    <br>
  <% end %>
  <hr>
  <div id="share-box">
    <p>Share "<%= @post.title %>"</p>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-google-plus"></i></a>
  </div>
  <hr>
  <%= link_to 'Back', root_path %>
  <%= render 'disqus' %>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h3><%= pluralize(@project.errors.count, "error") %> prevented this project from being saved: </h3>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %> <br>
  <%= f.text_field :title, placeholder: 'Title' %>
  <br><br>
  <%= f.label :link %> <br>
  <%= f.text_field :link, placeholder: 'Project URL' %>
  <br><br>
  <%= f.label :description %> <br>
  <%= f.text_area :description, placeholder: 'Your project\'s description goes here' %>
  <br><br>
  <%= f.submit %>
<% end %>
<br>
<%= link_to 'Cancel', projects_path %>

app/views/projects/edit.html.erb
<h1 id="page-title">Edit Project</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page-title">Things I've built</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <div class="post">
    <% if @projects.any? %>
      <% @projects.each do |project| %>
        <p class="date"><%= project.created_at.strftime('%A, %d %b %Y') %></p>
        <h2><a href="#"><%= link_to project.title, project %></a></h2>
        <br>
        <hr>
      <% end %>
    <% else %>
      <h3>No projects added yet.</h3>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to 'Add a project', new_project_path %>
    <% end %>
  </div>
  <br>
</div>

app/views/projects/new.html.erb
<h1 id="page-title">New Project</h1>
<div class="skinny-wrapper wrapper-padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post-show-content" class="skinny-wrapper wrapper-padding">
  <header>
    <p class="date"><%= @project.created_at.strftime('%A, %d %b %Y') %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>

  <div id="content">
    <%= markdown @project.description %><br>
    <div class="button-wrapper">
      <a href="<%= @project.link %>" class="project-button" target="_blank">Visit <%= @project.title %></a>
    </div>
    <br><br>
  </div>
  <% if user_signed_in? %>
    <div id="admin-links">
      <%= link_to 'Edit', edit_project_path(@project) %> |
      <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?'} %>
    </div>
    <br><br>
  <% end %>
    <%= link_to 'Back', root_path %>
    <hr>
</div>

app/views/welcome/_interests.html.erb
<div id="interests"> <!-- Interests -->
  <br>
  <h4>Things I am interested in and would love to explore in the future</h4>
  <br>
  <div class="insterests-box">
    <ul class="row">
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("angular.jpg"), "https://angularjs.org/", html: { alt: "Angular logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("jquery.jpg"), "http://jquery.com/", html: { alt: "jQuery logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("coffeescript.png"), "http://coffeescript.org/", html: { alt: "CoffeeScript logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("ajax.jpg"), "https://developer.mozilla.org/en/docs/AJAX", html: { alt: "AJAX logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("json.png"), "http://www.json.org/", html: { alt: "JSON logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("haml.jpg"), "http://haml.info/", html: { alt: "HAML logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("java.png"), "http://www.oracle.com/technetwork/java/index.html", html: { alt: "Java logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("clojure.png"), "http://clojure.org/", html: { alt: "Clojure logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("scala.jpg"), "http://www.scala-lang.org/", html: { alt: "Scala logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("database.png"), "http://en.wikipedia.org/wiki/Database", html: { alt: "Database logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("android.png"), "http://developer.android.com/index.html", html: { alt: "Android logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("apple_apps.jpg"), "https://developer.apple.com/devcenter/ios/index.action", html: { alt: "Apple Apps logo" } %></li>
    </ul>
    <br class="clear" />
  </div>
</div>

app/views/welcome/_skills.html.erb
<div id="skills"> <!-- Skills -->
  <br>
  <h4>Some of the amazing things I have been trained on at Makers Academy</h4>
  <br>
  <div class="skills-box">
    <ul class="row">
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("ruby.png"), "https://www.ruby-lang.org/en/", html: { alt: "Ruby logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("rails.png"), "http://rubyonrails.org/", html: { alt: "Rails logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("sinatra.jpg"), "http://www.sinatrarb.com/", html: { alt: "Sinatra logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("html5.jpg"), "http://www.w3schools.com/html/", html: { alt: "HTML5 logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("css3.png"), "http://www.w3schools.com/css/css3_intro.asp", html: { alt: "CSS3 logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("javascript.png"), "https://developer.mozilla.org/en-US/docs/Web/JavaScript", html: { alt: "Javascript logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("postgresql.png"), "http://www.postgresql.org/", html: { alt: "PostgreSQL logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("github.png"), "https://github.com/", html: { alt: "GitHub logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("heroku.png"), "https://www.heroku.com/", html: { alt: "Heroku logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("rspec.png"), "http://rspec.info/", html: { alt: "RSpec logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("capybara.png"), "https://github.com/jnicklas/capybara", html: { alt: "Capybara logo" } %></li>
      <li class="col-sm-4 col-md-4"><%=link_to image_tag("bootstrap.jpg"), "http://getbootstrap.com/", html: { alt: "Bootstrap logo" } %></li>
    </ul>
    <br class="clear" />
  </div>
</div>

app/views/welcome/about.html.erb
<h1 id="page-title">About me</h1>
<div class="wrapper wrapper-padding clearfix">
  <div class="about homepage-content">
    <p>Hello and thank you for stopping by. My name is Charles.</p>
    <p>I'm a <a href="http://www.makersacademy.com">Makers Academy</a> graduate and former Senior Network Administrator. I'm also a Rubyist, Rails admirer, Javascript frameworks enthusiast, Test Driven Development advocate and overall technology explorer. My aim is to learn at least one new thing every single day.</p>
    <p>I am a natural explorer. I like to find out how things work and what makes them tick. I enjoy putting things apart and putting them back together even though sometimes I am left with a few "spare" bits. But that does not happen only to me, does it? </p>
    <p>I love writing code. What interests me most about software and web development is their dynamism. Nothing stays the same for a long period of time, everything is useful and recyclable, and nobody knows everything about everything. Writing code keeps me on my toes and that is a good thing. It pushes me forwards. It keeps me curious and I consider writing code as one of my daily pleasures. It does indeed drive me insane sometimes and I love the feeling.</p>
    <p>While retraining as a developer, I discovered Test Driven Development/Design (TDD) and Behaviour Drive Development/Design (BDD). Those are areas I intend to dive deeper and learn how to write test to apply to code I write. I particularly enjoy working with RSpec and Capybara. Now I intend to learn to work with Jasmine, Karma and Protractor. </p>
    <p>I mentioned I have trained at Makers Academy. Makers Academy is highly selective, 12-week full-time programme that teaches web development in London. The work they do is amazing and I had the pleasure to work with incredibly talented people; both lecturers and students. My experience at Makers was absolutely worth its value in gold.</p>
    <p>Now that I have completed my training, I am seeking work as a junior developer so as I can use my newly acquired skills and develop them even further. I would love to interact and collaborate with some incredibly passionate people who loves coding not as a job but something they have pleasure in doing.</p>
    <p>I am in search of great masters and great mentors.</p>
    <br>
    <%= render 'skills' %>
    <br>
    <%= render 'interests' %>
    <br>
    <p><%= link_to 'Back', root_path %></p>
  </div>
</div>

app/views/welcome/index.html.erb
<h1 id="page-title">Welcome</h1>
<div class="wrapper wrapper-padding clearfix">
  <div class="about homepage-content">
    <div class="index_me">
      <%= image_tag 'charles_de_barros.jpg' %>
    </div>
    <p>Hello and thank you for stopping by. My name is Charles.</p>
    <p>Before you continue, please keep in mind that <strong><em>I am in the process of redoing this site</em></strong> so please forgive me if something is broken and I missed it. Drop me a line and I will strive to have it fixed it as quickly as I can. Thank you.  ;)
    </p>
    <p>I'm a <a href="http://www.makersacademy.com/">Makers Academy</a> graduate and former Senior Network Administrator. I'm also a Rubyist, Rails admirer, Test Driven Development advocate and overal technology explorer. My aim is to learn at least one new thing every single day.</p>
    <p>I am a natural explorer. I like to find out how things work and what makes them tick. I enjoy putting things apart and putting them back together. Though sometimes I am left with a few "spare" bits. But that does not happen only to me, does it? </p>
    <p><%= link_to 'Read more', welcome_about_path %></p>
  </div>
</div>